Feature skeleton
UIoT/uiot.github.io pull request #14
Opened 2017-09-28 18:53 UTC by gresendesa

These modifications are pretty much the same files split into sections. The basic directory structure was built as well.

2017-09-28 22:10 UTC, ovflowd requested changes
Please change those requested changes.

Thanks!

2017-09-28 22:10 UTC, sant0ro commented on .idea/uiot.github.io.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Remove this file, please.

2017-09-28 22:10 UTC, sant0ro commented on Gemfile
> +#gem 'jekyll-minifier'
Don't comment those modules.

2017-09-28 22:10 UTC, sant0ro commented on Gemfile.lock
>        public_suffix (>= 2.0.2, < 4.0)
Don't add the Gemfile.lock to the server. Ignore it on `.gitignore`

2017-09-29 14:05 UTC, gresendesa commented
I'll do it again

2017-09-29 14:05 UTC, closed without merging