Feature members
UIoT/uiot.github.io pull request #17
Opened 2017-10-09 17:55 UTC by FelipeDeAngelis

Coded the basics of the member system.

2017-10-09 23:19 UTC, ovflowd reviewed
The code seems to be OK, waiting for final changes. Remember to uncomment the `plugins` section from the `_config.yml` file.

Remember: this pull request only needs to merged after finishing the design and code of the whole section.

Tagging @IgorDias for the design.

2017-10-09 23:27 UTC, igordias submitted a review, later dismissed

2017-10-10 00:21 UTC, ovflowd requested changes
As combined, requesting changes.

The design need be concluded, @IgorDias will help.

2017-11-18 13:05 UTC, lucasmauricio commented
The initial version of about members page approved. Some improvements must be done in the future.
Nice job @FelipeDeAngelis!

2017-11-18 13:05 UTC, merged